FROM golang:1.17.0-alpine3.14 AS GO_BUILD
RUN mkdir /app
ADD . /app
WORKDIR /app
RUN go mod init main
RUN go build -o main .

FROM alpine:3
WORKDIR /app
COPY --from=GO_BUILD /app ./
EXPOSE 8080
CMD ["/app/main"]
