version: '3'

services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:80
  website:
    image: php:7.2-apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 80:80
    depends_on:
      - product-service
